#!/usr/bin/env bash

OWNER=cpanel
REPO=elevate-actions
COMMIT=dcba4f168b5aa17dc46fe04e8ba00691580765ba
CHECK_NAME="Dave Check"

gh api \
  --method POST \
  -H "Accept: application/vnd.github+json" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  /repos/${OWNER}/${REPO}/check-runs \
  -f "name=${CHECK_NAME}" \
  -f "head_sha=${COMMIT}" \
  -f "status=in_progress" \
  -f "external_id=42" \
  -f "started_at=2018-05-04T01:14:52Z" \
  -f "output[title]=The Report of all reports" \
  -f "output[summary]=Things went boomski" \
  -f "output[text]=May want to run another check, there, boss."
